pan_tilt:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    
    # Position Controllers ---------------------------------------
    tilt_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: tilt_joint
      pid: {p: 10.0, i: 1.0, d: 0.0}
    pan_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: pan_joint
      pid: {p: 10.0, i: 1.0, d: 0.0}
      
